### ISSUE TITLE
Too many dynamic allocations

### ISSUE THREAD

**Issue by LU15W1R7H** [Equilibrium-Games/Flounder#9]
In my opinion, you are overusing dynamic allocation. If it isn't necessary, you should avoid it, because it is a very slow operation. I don't see the point of making most members of a class pointers to dynamic memory. Please consider changing this.

**Comment by mattparks** [comment]
There are areas where this can definitely be reduced, mainly in file loading and per-frame updates (used minimally for this currently). A lot of the time dynamic allocations are used in objects where the lifetime lasts the runtime length. I will definitely start to remove dynamic allocation usages starting now, thanks for the feedback.

**Comment by LU15W1R7H** [comment]
Great! By the way: Nice game engine!
